#%RAML 0.8
title: assets
baseUri: https://amsdemo.iqmetrix.net

/assets:
    uriParameters:
          
      
    post:
        displayName: Creating an Asset
        headers:
            
            Authorization:
                example: Bearer (Access Token)
            
            Accept:
                example: application/json
            
            Content-Type:
                example: multipart/form-data
            
        body:
            
            multipart/form-data:
                
                formParameters:
                    
                    Filename:
                        displayName: Filename
                        description: |
                            File to be uploaded
                        required: true
                        type: file
                        example: image.jpg
                    
                
                
            
    

/assets/{AssetId}:
    uriParameters:
        
        AssetId:
            displayName: AssetId
            type: string
            example: 09fe1ee4-42b1-43a6-bd80-cd2bda21e90a
            description: |
                Identifier for the {{Asset}} 
            required: true
          
      
    get:
        displayName: Getting an Asset
        headers:
            
            Accept:
                example: application/json
            
        body:
            
    

/images/{AssetId}:
    uriParameters:
        
        AssetId:
            displayName: AssetId
            type: string
            example: 09fe1ee4-42b1-43a6-bd80-cd2bda21e90a
            description: |
                Identifier for the {{Asset}} 
            required: true
          
      
    get:
        displayName: Redirecting to an Image Asset
        headers:
            
        body:
            
    
