#%RAML 0.8
title: field-definitions
baseUri: https://productlibrarydemo.iqmetrix.net/v1

/FieldDefinitions:
    uriParameters:
          
      
    get:
        displayName: Getting All Field Definitions
        headers:
            
            Authorization:
                example: Bearer (Access Token)
            
            Accept:
                example: application/json
            
        body:
            
    

/FieldDefinitions({FieldDefinitionId}):
    uriParameters:
        
        FieldDefinitionId:
            displayName: FieldDefinitionId
            type: integer
            example: 1
            description: |
                Identifier for the {{FieldDefinition}} 
            required: true
          
      
    get:
        displayName: Getting a Field Definition
        headers:
            
            Authorization:
                example: Bearer (Access Token)
            
            Accept:
                example: application/json
            
        body:
            
    
