#%RAML 0.8
title: general-ledger
baseUri: https://generalledgerdemo.iqmetrix.net/v1

/Companies({CompanyId})/Accounts?$skip={Skip}&$top={Top}:
    uriParameters:
        
        CompanyId:
            displayName: CompanyId
            type: integer
            example: 14146
            description: |
                Identifier for the {{Company}} 
            required: true
        
        Skip:
            displayName: skip
            type: integer
            example: 0
            description: |
                Number of records to skip 
            required: false
        
        Top:
            displayName: top
            type: integer
            example: 5
            description: |
                Number of records to take 
            required: false
          
      
    get:
        displayName: Getting Accounts
        headers:
            
            Authorization:
                example: Bearer (Access Token)
            
            Accept:
                example: application/hal+json
            
        body:
            
    

/Companies({CompanyId})/Transactions?$filter=TransactionDateUTC ge datetime'{StartDate}' and TransactionDateUTC le datetime'{EndDate}'&$skip={Skip}&$top={Top}:
    uriParameters:
        
        CompanyId:
            displayName: CompanyId
            type: integer
            example: 14146
            description: |
                Identifier for the {{Company}} 
            required: true
        
        Skip:
            displayName: skip
            type: integer
            example: 0
            description: |
                Number of records to skip 
            required: false
        
        Top:
            displayName: top
            type: integer
            example: 5
            description: |
                Number of records to take 
            required: false
        
        StartDate:
            displayName: StartDate
            type: string
            example: Wed Dec 31 2014 18:00:00 GMT-0600 (Canada Central Standard Time)
            description: |
                Date at which to begin search request, in UTC 
            required: true
        
        EndDate:
            displayName: EndDate
            type: string
            example: Thu Dec 31 2015 17:59:59 GMT-0600 (Canada Central Standard Time)
            description: |
                Date at which to end search request, in UTC 
            required: true
          
      
    get:
        displayName: Getting Transactions By Date
        headers:
            
            Authorization:
                example: Bearer (Access Token)
            
            Accept:
                example: application/hal+json
            
        body:
            
    
