#%RAML 0.8
title: partner relationships
baseUri: https://entitymanagerdemo.iqmetrix.net/v1

/Partners({PartnerId})/Relationships/Companies?$skip={Skip}&$top={Top}:
    uriParameters:
        
        PartnerId:
            displayName: PartnerId
            type: integer
            example: 36
            description: |
                Identifier for the Partner 
            required: true
        
        Skip:
            displayName: skip
            type: integer
            example: 1
            description: |
                Number of records to skip, defaults to 0 
            required: false
        
        Top:
            displayName: top
            type: integer
            example: 10
            description: |
                Number of records to take, defaults to 20 
            required: false
          
      
    get:
        displayName: Getting Company Relationships for a Partner
        headers:
            
            Authorization:
                example: Bearer (Access Token)
            
            Accept:
                example: application/json
            
        body:
            
    
