#%RAML 0.8
title: partner reporting
baseUri: https://reportingdemo.iqmetrix.net/v1

/partners({PartnerId})/salesTransactions?startDate={StartDate}&endDate={EndDate}&$skip={Skip}&$top={Top}:
    uriParameters:
        
        PartnerId:
            displayName: PartnerId
            type: integer
            example: 36
            description: |
                Identifier for the {{Partner}} 
            required: true
        
        StartDate:
            displayName: StartDate
            type: string
            example: Wed Dec 02 2015 18:00:00 GMT-0600 (Canada Central Standard Time)
            description: |
                Date at which to begin search request 
            required: true
        
        EndDate:
            displayName: EndDate
            type: string
            example: Tue Dec 29 2015 18:00:00 GMT-0600 (Canada Central Standard Time)
            description: |
                Date at which to end search request 
            required: true
        
        Skip:
            displayName: Skip
            type: integer
            example: 0
            description: |
                Number of records to skip 
            required: false
        
        Top:
            displayName: Top
            type: integer
            example: 10
            description: |
                Number of records to take. Must be in the range [1-100]. Defaults to 20. 
            required: false
          
      
    get:
        displayName: Getting Sales Transactions
        headers:
            
            Authorization:
                example: Bearer (Access Token)
            
            Accept:
                example: application/json
            
        body:
            
    
