#%RAML 0.8
title: pricing
baseUri: https://pricingdemo.iqmetrix.net/v1

/Companies({CompanyId})/Pricing:
    uriParameters:
        
        CompanyId:
            displayName: CompanyId
            type: integer
            example: 14146
            description: |
                Identifier for the {{Company}} 
            required: true
          
      
    post:
        displayName: Creating or Updating Product Pricing at Company Level
        headers:
            
            Authorization:
                example: Bearer (Access Token)
            
            Accept:
                example: application/json
            
            Content-Type:
                example: application/json
            
        body:
            
            application/json:
                
                
                example: |  
                    {"Id":16446,"CatalogItemId":"a183f1a9-c58f-426a-930a-9a6357db52ed","CompanyId":14146,"EntityId":14202,"FloorPrice":3.99,"IsDiscountable":false,"OriginalPrice":4.99,"OverridePrice":3.99,"PricingTermId":78,"RegularPrice":10}
                
            
    

/Companies({CompanyId})/Entities({LocationId})/CatalogItems({CatalogItemId})/Pricing:
    uriParameters:
        
        CompanyId:
            displayName: CompanyId
            type: integer
            example: 14146
            description: |
                Identifier for the {{Company}} 
            required: true
        
        LocationId:
            displayName: LocationId
            type: string
            example: 14202
            description: |
                Identifier for the {{Location}} 
            required: true
        
        CatalogItemId:
            displayName: CatalogItemId
            type: string
            example: a183f1a9-c58f-426a-930a-9a6357db52ed
            description: |
                Unique identifier for the {{CatalogItem}} 
            required: true
          
      
    post:
        displayName: Creating or Updating Product Pricing at Location Level
        headers:
            
            Authorization:
                example: Bearer (Access Token)
            
            Accept:
                example: application/json
            
            Content-Type:
                example: application/json
            
        body:
            
            application/json:
                
                
                example: |  
                    {"Id":16446,"CatalogItemId":"a183f1a9-c58f-426a-930a-9a6357db52ed","CompanyId":14146,"EntityId":14202,"FloorPrice":3.99,"IsDiscountable":false,"OriginalPrice":4.99,"OverridePrice":3.99,"PricingTermId":78,"RegularPrice":10}
                
            
      
    get:
        displayName: Getting Product Pricing for a Retail Location
        headers:
            
            Authorization:
                example: Bearer (Access Token)
            
            Accept:
                example: application/json
            
        body:
            
    

/Companies({CompanyId})/CatalogItems({CatalogItemId})/Pricing:
    uriParameters:
        
        CompanyId:
            displayName: CompanyId
            type: integer
            example: 14146
            description: |
                Identifier for the {{Company}} 
            required: true
        
        CatalogItemId:
            displayName: CatalogItemId
            type: string
            example: a183f1a9-c58f-426a-930a-9a6357db52ed
            description: |
                Unique identifier for the {{CatalogItem}} 
            required: true
          
      
    get:
        displayName: Getting Product Pricing at Company Level
        headers:
            
            Authorization:
                example: Bearer (Access Token)
            
            Accept:
                example: application/json
            
        body:
            
    

/Companies({CompanyId})/PricingTerms:
    uriParameters:
        
        CompanyId:
            displayName: CompanyId
            type: integer
            example: 14146
            description: |
                Identifier for the {{Company}} 
            required: true
          
      
    get:
        displayName: Getting all Active Pricing Terms
        headers:
            
            Authorization:
                example: Bearer (Access Token)
            
            Accept:
                example: application/json
            
            Accept-Language:
                example: en-US
            
        body:
            
    

/Companies({CompanyId})/PricingTerms({PricingTermId}):
    uriParameters:
        
        CompanyId:
            displayName: CompanyId
            type: integer
            example: 14146
            description: |
                Identifier for the {{Company}} 
            required: true
        
        PricingTermId:
            displayName: PricingTermId
            type: string
            example: 78
            description: |
                Identifier for the {{PricingTerm}} 
            required: true
          
      
    get:
        displayName: Getting a Pricing Term
        headers:
            
            Authorization:
                example: Bearer (Access Token)
            
            Accept:
                example: application/json
            
            Accept-Language:
                example: en-US
            
        body:
            
    

/Companies({CompanyId})/Pricing({PricingId})/SaleOverridePrices:
    uriParameters:
        
        CompanyId:
            displayName: CompanyId
            type: integer
            example: 14146
            description: |
                Identifier for the {{Company}} 
            required: true
        
        PricingId:
            displayName: PricingId
            type: integer
            example: 16446
            description: |
                Identifier for a {{Pricing}} 
            required: true
          
      
    post:
        displayName: Creating a Sale Price
        headers:
            
            Authorization:
                example: Bearer (Access Token)
            
            Accept:
                example: application/json
            
            Content-Type:
                example: application/json
            
        body:
            
            application/json:
                
                
                example: |  
                    {"Id":1177,"CompanyId":14146,"IsDefault":true,"PricingInformationId":16446,"SalePrice":3.99,"StartDateUTC":"2015-12-02T00:00:00","StopDateUTC":"2015-12-31T00:00:00"}
                
            
      
    get:
        displayName: Getting All Sale Pricing
        headers:
            
            Authorization:
                example: Bearer (Access Token)
            
            Accept:
                example: application/json
            
        body:
            
    

/Companies({CompanyId})/Pricing({PricingId})/SaleOverridePrices({SaleOverridePriceId}):
    uriParameters:
        
        CompanyId:
            displayName: CompanyId
            type: integer
            example: 14146
            description: |
                Identifier for the {{Company}} 
            required: true
        
        PricingId:
            displayName: PricingId
            type: integer
            example: 16446
            description: |
                Identifier for a {{Pricing}} 
            required: true
        
        SaleOverridePriceId:
            displayName: SaleOverridePriceId
            type: integer
            example: 2802
            description: |
                Identifier for a {{SaleOverridePrice}} 
            required: true
          
      
    put:
        displayName: Updating a Sale Pricing
        headers:
            
            Authorization:
                example: Bearer (Access Token)
            
            Accept:
                example: application/json
            
            Content-Type:
                example: application/json
            
        body:
            
            application/json:
                
                
                example: |  
                    {"Id":1177,"CompanyId":14146,"IsDefault":true,"PricingInformationId":16446,"SalePrice":3.99,"StartDateUTC":"2015-12-02T00:00:00","StopDateUTC":"2015-12-31T00:00:00"}
                
            
      
    delete:
        displayName: Deleting a Sale Pricing
        headers:
            
            Authorization:
                example: Bearer (Access Token)
            
        body:
            
    

/Companies({CompanyId})/CatalogItems({CatalogItemId})/Pricing?$filter={PricingTermId}:
    uriParameters:
        
        CompanyId:
            displayName: CompanyId
            type: integer
            example: 14146
            description: |
                Identifier for the {{Company}} 
            required: true
        
        CatalogItemId:
            displayName: CatalogItemId
            type: string
            example: a183f1a9-c58f-426a-930a-9a6357db52ed
            description: |
                Unique identifier for the {{CatalogItem}} 
            required: true
        
        PricingTermId:
            displayName: PricingTermId
            type: string
            example: 78
            description: |
                Identifier for the {{PricingTerm}} 
            required: true
          
      
    get:
        displayName: Getting Product Pricing by Pricing Term
        headers:
            
            Authorization:
                example: Bearer (Access Token)
            
            Accept:
                example: application/json
            
        body:
            
    
