#%RAML 0.8
title: product structure
baseUri: https://productlibrarydemo.iqmetrix.net/v1

/ProductDocs:
    uriParameters:
          
      
    post:
        displayName: Creating a Master Product
        headers:
            
            Authorization:
                example: Bearer (Access Token)
            
            Accept:
                example: application/json
            
            Content-Type:
                example: application/json
            
        body:
            
            application/json:
                
                
                example: |  
                    {"Classification":{"TreeId":1,"Id":4,"Name":"Smartphones"},"ColorDefinitions":[{"Id":"5c6e2779-79d1-4fbd-b6a8-36b81e851b15","Name":"Black Sapphire","ColorTagIds":[1],"ColorTags":[{"Id":1,"Name":"Black","ColorCode":"#303232"}],"Swatch":{"Type":"ColorCode","AssetId":"null","ColorCode":"#C0C8D0"}}],"Manufacturer":{"Id":13149,"Name":"OtterBox"},"OwnerEntityId":14146,"RootRevision":{"Assets":[{"Id":"a130e8f0-ddb1-4034-a34a-53d3ac03d384","Name":"HeroShot","MimeType":"image/jpeg","IsHidden":false}],"ColorDefinitionId":"5c6e2779-79d1-4fbd-b6a8-36b81e851b15","FieldValues":[{"FieldDefinitionId":1,"LanguageInvariantValue":"iPhone 4S 16 GB Black"}],"IdentifierGroups":[{"Type":"ManufacturerSKU","ForceOverride":false,"Identifiers":[{"Description":"Manufacturer sku","Entity":{"Id":14146,"Name":"Kentel Corp"},"Type":"ManufacturerSKU","Value":"ManufacturerSKU"}]}]}}
                
            
    

/ProductDocs({ProductDocumentId}):
    uriParameters:
        
        ProductDocumentId:
            displayName: ProductDocumentId
            type: integer
            example: 8
            description: |
                Identifier for a {{ProductDocument}} 
            required: true
          
      
    get:
        displayName: Getting a Product Hierarchy
        headers:
            
            Authorization:
                example: Bearer (Access Token)
            
            Accept:
                example: application/json
            
        body:
            
      
    put:
        displayName: Updating a Master Product
        headers:
            
            Authorization:
                example: Bearer (Access Token)
            
            Accept:
                example: application/json
            
            Content-Type:
                example: application/json
            
        body:
            
            application/json:
                
                
                example: |  
                    {"Assets":[{"Id":"a130e8f0-ddb1-4034-a34a-53d3ac03d384","Name":"HeroShot","MimeType":"image/jpeg","IsHidden":false}],"ColorDefinitionId":"5c6e2779-79d1-4fbd-b6a8-36b81e851b15","FieldValues":[{"FieldDefinitionId":1,"LanguageInvariantValue":"iPhone 4S 16 GB Black"}],"IdentifierGroups":[{"Type":"ManufacturerSKU","ForceOverride":false,"Identifiers":[{"Description":"Manufacturer sku","Entity":{"Id":14146,"Name":"Kentel Corp"},"Type":"ManufacturerSKU","Value":"ManufacturerSKU"}]}]}
                
            
    

/ProductDocs({ProductDocumentId})/Variations:
    uriParameters:
        
        ProductDocumentId:
            displayName: ProductDocumentId
            type: integer
            example: 8
            description: |
                Identifier for a {{ProductDocument}} 
            required: true
          
      
    post:
        displayName: Creating a Variation
        headers:
            
            Authorization:
                example: Bearer (Access Token)
            
            Accept:
                example: application/json
            
            Content-Type:
                example: application/json
            
        body:
            
            application/json:
                
                
                example: |  
                    {"Assets":[{"Id":"a130e8f0-ddb1-4034-a34a-53d3ac03d384","Name":"HeroShot","MimeType":"image/jpeg","IsHidden":false}],"ColorDefinitionId":"5c6e2779-79d1-4fbd-b6a8-36b81e851b15","FieldValues":[{"FieldDefinitionId":1,"LanguageInvariantValue":"iPhone 4S 16 GB Black"}],"IdentifierGroups":[{"Type":"ManufacturerSKU","ForceOverride":false,"Identifiers":[{"Description":"Manufacturer sku","Entity":{"Id":14146,"Name":"Kentel Corp"},"Type":"ManufacturerSKU","Value":"ManufacturerSKU"}]}]}
                
            
    

/ProductDocs({ProductDocumentId})/Variations?variationId={VariationId}:
    uriParameters:
        
        ProductDocumentId:
            displayName: ProductDocumentId
            type: integer
            example: 8
            description: |
                Identifier for a {{ProductDocument}} 
            required: true
        
        VariationId:
            displayName: VariationId
            type: integer
            example: 1
            description: |
                Identifier of the {{Variation}}. To get a list of Variations for a Product, see <a href="#getting-a-product-hierarchy">Getting a Product Hierarchy</a> 
            required: true
          
      
    put:
        displayName: Updating a Variation
        headers:
            
            Authorization:
                example: Bearer (Access Token)
            
            Accept:
                example: application/json
            
            Content-Type:
                example: application/json
            
        body:
            
            application/json:
                
                
                example: |  
                    {"Assets":[{"Id":"a130e8f0-ddb1-4034-a34a-53d3ac03d384","Name":"HeroShot","MimeType":"image/jpeg","IsHidden":false}],"ColorDefinitionId":"5c6e2779-79d1-4fbd-b6a8-36b81e851b15","FieldValues":[{"FieldDefinitionId":1,"LanguageInvariantValue":"iPhone 4S 16 GB Black"}],"IdentifierGroups":[{"Type":"ManufacturerSKU","ForceOverride":false,"Identifiers":[{"Description":"Manufacturer sku","Entity":{"Id":14146,"Name":"Kentel Corp"},"Type":"ManufacturerSKU","Value":"ManufacturerSKU"}]}]}
                
            
    

/ProductDocs({ProductDocumentId})/Revisions?variationId={VariationId}&countryCode={CountryCode}&stateCode={StateCode}&entityId={EntityId}:
    uriParameters:
        
        ProductDocumentId:
            displayName: ProductDocumentId
            type: integer
            example: 8
            description: |
                Identifier for a {{ProductDocument}} 
            required: true
        
        VariationId:
            displayName: VariationId
            type: integer
            example: 4
            description: |
                Identifier for a {{Variation}}, to get a list of Variations for a Product, see <a href="#getting-a-product-hierarchy">Getting a Product Hierarchy</a> 
            required: false
        
        CountryCode:
            displayName: CountryCode
            type: string
            example: CA
            description: |
                Two letter country code for a Country. Uses the ISO 3166-1 alpha-2 standard 
            required: false
        
        StateCode:
            displayName: StateCode
            type: string
            example: MB
            description: |
                Two letter state code for a State or Province. Based off the ISO 3166-2 standard 
            required: false
        
        EntityId:
            displayName: EntityId
            type: integer
            example: 1
            description: |
                Identifier for a {{Company}} or {{Carrier}} 
            required: false
          
      
    post:
        displayName: Creating a Revision
        headers:
            
            Authorization:
                example: Bearer (Access Token)
            
            Accept:
                example: application/json
            
            Content-Type:
                example: application/json
            
        body:
            
            application/json:
                
                
                example: |  
                    {"Id":5,"ColorDefinitionId":"5c6e2779-79d1-4fbd-b6a8-36b81e851b15","Entity":{"Id":14146,"Name":"Kentel Corp"},"FieldValues":[{"FieldDefinitionId":1,"LanguageInvariantValue":"iPhone 4S 16 GB Black"}],"IdentifierGroups":[{"Type":"ManufacturerSKU","ForceOverride":false,"Identifiers":[{"Description":"Manufacturer sku","Entity":{"Id":14146,"Name":"Kentel Corp"},"Type":"ManufacturerSKU","Value":"ManufacturerSKU"}]}],"Regions":[{"CountryCode":"CA","CountryName":"Canada","StateCode":"AB","StateName":"British Columbia"}]}
                
            
      
    put:
        displayName: Updating a Revision
        headers:
            
            Authorization:
                example: Bearer (Access Token)
            
            Accept:
                example: application/json
            
            Content-Type:
                example: application/json
            
        body:
            
            application/json:
                
                
                example: |  
                    {"Id":5,"ColorDefinitionId":"5c6e2779-79d1-4fbd-b6a8-36b81e851b15","Entity":{"Id":14146,"Name":"Kentel Corp"},"FieldValues":[{"FieldDefinitionId":1,"LanguageInvariantValue":"iPhone 4S 16 GB Black"}],"IdentifierGroups":[{"Type":"ManufacturerSKU","ForceOverride":false,"Identifiers":[{"Description":"Manufacturer sku","Entity":{"Id":14146,"Name":"Kentel Corp"},"Type":"ManufacturerSKU","Value":"ManufacturerSKU"}]}],"Regions":[{"CountryCode":"CA","CountryName":"Canada","StateCode":"AB","StateName":"British Columbia"}]}
                
            
    

/ProductDocs({ProductDocumentId})/ColorDefinitions:
    uriParameters:
        
        ProductDocumentId:
            displayName: ProductDocumentId
            type: integer
            example: 8
            description: |
                Identifier for a {{ProductDocument}} 
            required: true
          
      
    get:
        displayName: Getting Color Definitions
        headers:
            
            Authorization:
                example: Bearer (Access Token)
            
            Accept:
                example: application/json
            
        body:
            
      
    post:
        displayName: Creating a Color Definition
        headers:
            
            Authorization:
                example: Bearer (Access Token)
            
            Accept:
                example: application/json
            
            Content-Type:
                example: application/json
            
        body:
            
            application/json:
                
                
                example: |  
                    {"ColorDefinitions":[{"Id":"5c6e2779-79d1-4fbd-b6a8-36b81e851b15","Name":"Black Sapphire","ColorTagIds":[1],"ColorTags":[{"Id":1,"Name":"Black","ColorCode":"#303232"}],"Swatch":{"Type":"ColorCode","AssetId":"null","ColorCode":"#C0C8D0"}}]}
                
            
    

/ColorTags:
    uriParameters:
          
      
    get:
        displayName: Getting All Color Tags
        headers:
            
            Authorization:
                example: Bearer (Access Token)
            
            Accept:
                example: application/json
            
        body:
            
    
