#%RAML 0.8
title: punch-clock
baseUri: https://punchclockdemo.iqmetrix.net/v1

/Companies({CompanyId})/PunchEntries?$filter=LastUpdateDateUtc ge datetime'{StartDate}' and LastUpdateDateUtc le datetime'{EndDate}'&$skip={Skip}&$top={Top}:
    uriParameters:
        
        CompanyId:
            displayName: CompanyId
            type: integer
            example: 14146
            description: |
                Identifier for the {{Company}} 
            required: true
        
        StartDate:
            displayName: StartDate
            type: string
            example: Wed Dec 31 2014 18:00:00 GMT-0600 (Canada Central Standard Time)
            description: |
                Date at which to begin search request, in UTC 
            required: false
        
        EndDate:
            displayName: EndDate
            type: string
            example: Thu Dec 31 2015 17:59:59 GMT-0600 (Canada Central Standard Time)
            description: |
                Date at which to end search request, in UTC 
            required: false
        
        Skip:
            displayName: skip
            type: integer
            example: 1
            description: |
                Number of records to skip 
            required: false
        
        Top:
            displayName: top
            type: integer
            example: 10
            description: |
                Number of records to take 
            required: false
          
      
    get:
        displayName: Getting All Punch Entries
        headers:
            
            Authorization:
                example: Bearer (Access Token)
            
            Accept:
                example: application/hal+json
            
        body:
            
    
