#%RAML 0.8
title: user-manager
baseUri: https://usermanagerdemo.iqmetrix.net/v1

/Users/importExisting:
    uriParameters:
          
      
    post:
        displayName: Importing an Existing User
        headers:
            
            Authorization:
                example: Bearer (Access Token)
            
            Accept:
                example: application/json
            
            Content-Type:
                example: application/json
            
        body:
            
            application/json:
                
                
                example: |  
                    {"UserName":"johnb@kentel","Password":"samplepassword","Email":"johnb@kentel.com","FirstName":"John","LastName":"Bates","ParentEntityId":1,"ClientUserId":"132","JobTitle":"Sales Clerk","Address":{"AddressLine1":"1432 Merry View Road","AddressLine2":"","City":"Big Windy","StateCode":"ON","CountryCode":"CA","Zip":"A1A2B2"},"PhoneNumbers":[{"Number":"6135550127","Extension":"5532","Type":"Work"}]}
                
            
    

/Users({UserId}):
    uriParameters:
        
        UserId:
            displayName: UserId
            type: string
            example: 2576
            description: |
                Identifier for the {{User}} 
            required: true
          
      
    get:
        displayName: Getting a User
        headers:
            
            Authorization:
                example: Bearer (Access Token)
            
            Accept:
                example: application/json
            
        body:
            
      
    put:
        displayName: Updating a User
        headers:
            
            Authorization:
                example: Bearer (Access Token)
            
            Accept:
                example: application/json
            
            Content-Type:
                example: application/json
            
        body:
            
            application/json:
                
                
                example: |  
                    {"Id":2576,"FirstName":"John","LastName":"Bates","UserName":"johnb@kentel.com","Address":{"AddressLine1":"1432 Merry View Road","AddressLine2":"","City":"Big Windy","StateCode":"ON","CountryCode":"CA","Zip":"A1A2B2"},"ClientUserId":"132","Email":"johnb@kentel.com","IsActive":true,"JobTitle":"Sales Clerk","ParentEntityId":1,"PhoneNumbers":[{"Number":"6135550127","Extension":"5532","Type":"Work"}],"Picture":{},"Version":1}
                
            
      
    delete:
        displayName: Disabling a User
        headers:
            
            Authorization:
                example: Bearer (Access Token)
            
        body:
            
    

/Entities({CompanyId})/Users?$skip={Skip}&$top={Top}:
    uriParameters:
        
        CompanyId:
            displayName: CompanyId
            type: integer
            example: 14146
            description: |
                Identifier for the {{Company}} 
            required: true
        
        Skip:
            displayName: skip
            type: integer
            example: 1
            description: |
                Number of records to skip 
            required: false
        
        Top:
            displayName: top
            type: integer
            example: 10
            description: |
                Number of records to take 
            required: false
          
      
    get:
        displayName: Getting All Users for a Company
        headers:
            
            Authorization:
                example: Bearer (Access Token)
            
            Accept:
                example: application/json
            
        body:
            
    

/Entities({CompanyId})/Users/Search?terms={Terms}&$skip={Skip}&$top={Top}:
    uriParameters:
        
        CompanyId:
            displayName: CompanyId
            type: integer
            example: 14146
            description: |
                Identifier for the {{Company}} 
            required: true
        
        Terms:
            displayName: terms
            type: string
            example: Sam+Smith
            description: |
                List of terms, multiple terms are separated by an encoded whitespace (+). User properties must contain/start with the term to be returned. Search terms are not case sensitive. 
            required: true
        
        Skip:
            displayName: skip
            type: integer
            example: 1
            description: |
                Number of records to skip 
            required: false
        
        Top:
            displayName: top
            type: integer
            example: 10
            description: |
                Number of records to take 
            required: false
          
      
    get:
        displayName: Searching for Users
        headers:
            
            Authorization:
                example: Bearer (Access Token)
            
            Accept:
                example: application/json
            
        body:
            
    

/Users({UserId})/Locations({LocationId}):
    uriParameters:
        
        UserId:
            displayName: UserId
            type: integer
            example: 2576
            description: |
                Identifier for the {{User}} 
            required: true
        
        LocationId:
            displayName: LocationId
            type: integer
            example: 2
            description: |
                Identifier for the {{Location}} 
            required: true
          
      
    put:
        displayName: Assigning a User to a Location
        headers:
            
            Authorization:
                example: Bearer (Access Token)
            
            Accept:
                example: application/json
            
            Content-Type:
                example: application/json
            
        body:
            
      
    delete:
        displayName: Unassigning a User from a Location
        headers:
            
            Authorization:
                example: Bearer (Access Token)
            
            Accept:
                example: application/json
            
        body:
            
    

/Users({UserId})/Locations:
    uriParameters:
        
        UserId:
            displayName: UserId
            type: integer
            example: 2576
            description: |
                Identifier for the {{User}} 
            required: true
          
      
    get:
        displayName: Getting Assigned Locations for a User
        headers:
            
            Authorization:
                example: Bearer (Access Token)
            
            Accept:
                example: application/json
            
        body:
            
    

/Entities({CompanyId})/Users?$filter=ClientUserId eq '{ClientUserId}'&$skip={Skip}&$top={Top}:
    uriParameters:
        
        CompanyId:
            displayName: CompanyId
            type: integer
            example: 14146
            description: |
                Identifier for the {{Company}} 
            required: true
        
        ClientUserId:
            displayName: ClientUserId
            type: string
            example: 132
            description: |
                Identifier for the {{User}} in an external system 
            required: true
        
        Skip:
            displayName: skip
            type: integer
            example: 1
            description: |
                Number of records to skip 
            required: false
        
        Top:
            displayName: top
            type: integer
            example: 10
            description: |
                Number of records to take 
            required: false
          
      
    get:
        displayName: Getting Users by ClientUserId
        headers:
            
            Authorization:
                example: Bearer (Access Token)
            
            Accept:
                example: application/json
            
        body:
            
    

/Users({UserId})/Lock:
    uriParameters:
        
        UserId:
            displayName: UserId
            type: integer
            example: 2576
            description: |
                Identifier for the {{User}} 
            required: true
          
      
    post:
        displayName: Locking a User
        headers:
            
            Authorization:
                example: Bearer (Access Token)
            
            Accept:
                example: application/json
            
            Content-Type:
                example: application/json
            
        body:
            
            application/json:
                
                
                example: |
                    {
                      "LockReasonId": 14
                    }
                    

                
            
    

/Users({UserId})/Unlock:
    uriParameters:
        
        UserId:
            displayName: UserId
            type: integer
            example: 2576
            description: |
                Identifier for the {{User}} 
            required: true
          
      
    get:
        displayName: Getting the Lock Status of a User
        headers:
            
            Authorization:
                example: Bearer (Access Token)
            
            Accept:
                example: application/json
            
        body:
            
      
    post:
        displayName: Unlocking a User
        headers:
            
            Authorization:
                example: Bearer (Access Token)
            
            Accept:
                example: application/json
            
            Content-Type:
                example: application/json
            
        body:
            
            application/json:
                
                
            
    

/Users({UserId})/Enable:
    uriParameters:
        
        UserId:
            displayName: UserId
            type: integer
            example: 2576
            description: |
                Identifier for the {{User}} 
            required: true
          
      
    post:
        displayName: Enabling a User
        headers:
            
            Authorization:
                example: Bearer (Access Token)
            
            Accept:
                example: application/json
            
            Content-Type:
                example: application/json
            
        body:
            
    

/Users({UserId})/TemporaryPassword:
    uriParameters:
        
        UserId:
            displayName: UserId
            type: integer
            example: 2576
            description: |
                Identifier for the {{User}} 
            required: true
          
      
    post:
        displayName: Setting a Temporary Password
        headers:
            
            Authorization:
                example: Bearer (Access Token)
            
            Accept:
                example: application/json
            
            Content-Type:
                example: application/json
            
        body:
            
            application/json:
                
                
                example: |  
                    {"Password":"newpa55word"}
                
            
    

/Entities({CompanyId})/lockReasons:
    uriParameters:
        
        CompanyId:
            displayName: CompanyId
            type: integer
            example: 14146
            description: |
                Identifier for the {{Company}} 
            required: true
          
      
    get:
        displayName: Getting all Lock Reasons
        headers:
            
            Authorization:
                example: Bearer (Access Token)
            
            Accept:
                example: application/json
            
        body:
            
      
    post:
        displayName: Creating a Lock Reason
        headers:
            
            Authorization:
                example: Bearer (Access Token)
            
            Accept:
                example: application/json
            
            Content-Type:
                example: application/json
            
        body:
            
            application/json:
                
                
                example: |  
                    {"Id":14,"Name":"PaperworkNotDone","Description":"Your account has been locked because the paperwork hasn't been done. Please contact your supervisor."}
                
            
    

/Entities({CompanyId})/lockReasons({LockReasonId}):
    uriParameters:
        
        CompanyId:
            displayName: CompanyId
            type: integer
            example: 14146
            description: |
                Identifier for the {{Company}} 
            required: true
        
        LockReasonId:
            displayName: LockReasonId
            type: integer
            example: 14
            description: |
                Identifier of a {{LockReason}} 
            required: true
          
      
    get:
        displayName: Getting a Lock Reason
        headers:
            
            Authorization:
                example: Bearer (Access Token)
            
            Accept:
                example: application/json
            
        body:
            
      
    put:
        displayName: Updating a Lock Reason
        headers:
            
            Authorization:
                example: Bearer (Access Token)
            
            Accept:
                example: application/json
            
            Content-Type:
                example: application/json
            
        body:
            
            application/json:
                
                
                example: |  
                    {"Id":14,"Name":"PaperworkNotDone","Description":"Your account has been locked because the paperwork hasn't been done. Please contact your supervisor."}
                
            
      
    delete:
        displayName: Deleting a Lock Reason
        headers:
            
            Authorization:
                example: Bearer (Access Token)
            
        body:
            
    
