#%RAML 0.8
title: catalog
baseUri: https://catalogsdemo.iqmetrix.net/v1

/Companies({CompanyId})/Catalog/Items:
    uriParameters:
        
        CompanyId:
            displayName: CompanyId
            type: integer
            example: 14146
            description: |
                Identifier for the {{Company}} 
            required: true
          
      
    get:
        displayName: Getting All Catalog Items
        headers:
            
            Authorization:
                example: Bearer (Access Token)
            
            Accept:
                example: application/json
            
        body:
            
      
    post:
        displayName: Adding a Catalog Item from Product Library
        headers:
            
            Authorization:
                example: Bearer (Access Token)
            
            Accept:
                example: application/json
            
            Content-Type:
                example: application/json
            
        body:
            
            application/json:
                
                
                example: |  
                    {"Slug":"M1248-V1"}
                
            
    

/Companies({CompanyId})/Catalog/Items({CatalogItemId})/ProductDetails:
    uriParameters:
        
        CompanyId:
            displayName: CompanyId
            type: integer
            example: 14146
            description: |
                Identifier for the {{Company}} 
            required: true
        
        CatalogItemId:
            displayName: CatalogItemId
            type: string
            example: a183f1a9-c58f-426a-930a-9a6357db52ed
            description: |
                Unique identifier for the {{CatalogItem}} 
            required: true
          
      
    get:
        displayName: Getting Product Details
        headers:
            
            Authorization:
                example: Bearer (Access Token)
            
            Accept:
                example: application/json
            
        body:
            
    

/Companies({CompanyId})/Catalog/Items({CatalogItemId})/Compatible:
    uriParameters:
        
        CompanyId:
            displayName: CompanyId
            type: integer
            example: 14146
            description: |
                Identifier for the {{Company}} 
            required: true
        
        CatalogItemId:
            displayName: CatalogItemId
            type: string
            example: a183f1a9-c58f-426a-930a-9a6357db52ed
            description: |
                Unique identifier for the {{CatalogItem}} 
            required: true
          
      
    get:
        displayName: Getting Compatible Products for a Catalog Item
        headers:
            
            Authorization:
                example: Bearer (Access Token)
            
            Accept:
                example: application/json
            
        body:
            
    

/Companies({CompanyId})/Catalog/Items({CatalogItemId})/Variations:
    uriParameters:
        
        CompanyId:
            displayName: CompanyId
            type: integer
            example: 14146
            description: |
                Identifier for the {{Company}} 
            required: true
        
        CatalogItemId:
            displayName: CatalogItemId
            type: string
            example: a183f1a9-c58f-426a-930a-9a6357db52ed
            description: |
                Unique identifier for the {{CatalogItem}} 
            required: true
          
      
    get:
        displayName: Getting Variations for a Catalog Item
        headers:
            
            Authorization:
                example: Bearer (Access Token)
            
            Accept:
                example: application/json
            
        body:
            
    

/Companies({CompanyId})/Catalog/Items/ByVendorSku?vendorsku={VendorSku}&vendorid={VendorId}:
    uriParameters:
        
        CompanyId:
            displayName: CompanyId
            type: integer
            example: 14146
            description: |
                Identifier for the {{Company}} 
            required: true
        
        VendorSku:
            displayName: VendorSku
            type: string
            example: 408853
            description: |
                Vendor SKU to search for 
            required: true
        
        VendorId:
            displayName: VendorId
            type: integer
            example: 1217
            description: |
                Identifier for a {{Vendor}} to search for 
            required: false
          
      
    get:
        displayName: Getting Products by Vendor SKU
        headers:
            
            Authorization:
                example: Bearer (Access Token)
            
            Accept:
                example: application/json
            
        body:
            
    

/Companies({CompanyId})/Catalog/Search?CategoryOrClassificationId={CategoryOrClassificationId}&Page={Page}&PageSize={PageSize}:
    uriParameters:
        
        CompanyId:
            displayName: CompanyId
            type: integer
            example: 14146
            description: |
                Identifier for the {{Company}} 
            required: true
        
        CategoryOrClassificationId:
            displayName: CategoryOrClassificationId
            type: string
            example: 1
            description: |
                Identifier for the {{Category}} or {{Classification}} 
            required: false
        
        Page:
            displayName: Page
            type: string
            example: 1
            description: |
                Page to display, if not specified defaults to 1 
            required: false
        
        PageSize:
            displayName: PageSize
            type: string
            example: 10
            description: |
                Number of results that will be returned, if not specified defaults to 20 
            required: false
          
      
    get:
        displayName: Getting Products by Category or Classification
        headers:
            
            Authorization:
                example: Bearer (Access Token)
            
            Accept:
                example: application/json
            
        body:
            
    

/Companies({CompanyId})/Catalog/Search?ManufacturerIds={ManufacturerIds}&Page={Page}&PageSize={PageSize}:
    uriParameters:
        
        CompanyId:
            displayName: CompanyId
            type: integer
            example: 14146
            description: |
                Identifier for the {{Company}} 
            required: true
        
        ManufacturerIds:
            displayName: ManufacturerIds
            type: string
            example: 10540
            description: |
                Array of integers representing identifiers for {{Manufacturers}} 
            required: false
        
        Page:
            displayName: Page
            type: string
            example: 1
            description: |
                Page to display, if not specified defaults to 1 
            required: false
        
        PageSize:
            displayName: PageSize
            type: string
            example: 10
            description: |
                Number of results that will be returned, if not specified defaults to 20 
            required: false
          
      
    get:
        displayName: Getting Products by Manufacturer
        headers:
            
            Authorization:
                example: Bearer (Access Token)
            
            Accept:
                example: application/json
            
        body:
            
    

/Companies({CompanyId})/Catalog/Search?VendorIds={VendorIds}&Page={Page}&PageSize={PageSize}:
    uriParameters:
        
        CompanyId:
            displayName: CompanyId
            type: integer
            example: 14146
            description: |
                Identifier for the {{Company}} 
            required: true
        
        VendorIds:
            displayName: VendorIds
            type: string
            example: 1217
            description: |
                List of comma seperated integers representing Supplier identifiers 
            required: false
        
        Page:
            displayName: Page
            type: string
            example: 1
            description: |
                Page to display, if not specified defaults to 1 
            required: false
        
        PageSize:
            displayName: PageSize
            type: string
            example: 10
            description: |
                Number of results that will be returned, if not specified defaults to 20 
            required: false
          
      
    get:
        displayName: Getting Products by Supplier
        headers:
            
            Authorization:
                example: Bearer (Access Token)
            
            Accept:
                example: application/json
            
        body:
            
    

/Companies({CompanyId})/Catalog/Search?IsDropshippable={IsDropShippable}&Page={Page}&PageSize={PageSize}:
    uriParameters:
        
        CompanyId:
            displayName: CompanyId
            type: integer
            example: 14146
            description: |
                Identifier for the {{Company}} 
            required: true
        
        IsDropShippable:
            displayName: IsDropshippable
            type: string
            example: true
            description: |
                True to display products available for shipping, false to display products not available for shipping 
            required: false
        
        Page:
            displayName: Page
            type: string
            example: 1
            description: |
                Page to display, if not specified defaults to 1 
            required: false
        
        PageSize:
            displayName: PageSize
            type: string
            example: 10
            description: |
                Number of results that will be returned, if not specified defaults to 20 
            required: false
          
      
    get:
        displayName: Getting Products Available for Shipping
        headers:
            
            Authorization:
                example: Bearer (Access Token)
            
            Accept:
                example: application/json
            
        body:
            
    

/Companies({CompanyId})/Catalog/Search?SearchTerms={SearchTerms}&OrderBy={OrderBy}&OrderDir={OrderDir}&Page={Page}&PageSize={PageSize}:
    uriParameters:
        
        CompanyId:
            displayName: CompanyId
            type: integer
            example: 14146
            description: |
                Identifier for the {{Company}} 
            required: true
        
        SearchTerms:
            displayName: SearchTerms
            type: string
            example: iPhone
            description: |
                Search terms 
            required: false
        
        OrderBy:
            displayName: OrderBy
            type: string
            example: name
            description: |
                A string value representing which field to order the results by. Acceptable values are name or dateAdded. Defaults to name if not specified 
            required: false
        
        OrderDir:
            displayName: OrderDir
            type: string
            example: asc
            description: |
                A string value representing the sort direction. Acceptable values are asc and desc. Defaults to asc if not specified 
            required: false
        
        Page:
            displayName: Page
            type: string
            example: 1
            description: |
                Page to display, if not specified defaults to 1 
            required: false
        
        PageSize:
            displayName: PageSize
            type: string
            example: 10
            description: |
                Number of results that will be returned, if not specified defaults to 20 
            required: false
          
      
    get:
        displayName: Searching For Products
        headers:
            
            Authorization:
                example: Bearer (Access Token)
            
            Accept:
                example: application/json
            
        body:
            
    

/Companies({CompanyId})/Catalog/Search?VendorIds={VendorIds}&ManufacturerIds={ManufacturerIds}&IsDropshippable={IsDropShippable}&CategoryOrClassificationId={CategoryOrClassificationId}&ClassificationTreeId={ClassificationTreeId}&SearchTerms={SearchTerms}&OrderBy={OrderBy}&OrderDir={OrderDir}&PrivateProduct={PrivateProduct}&ColorTagIds={ColorTagIds}&Page={Page}&PageSize={PageSize}:
    uriParameters:
        
        CompanyId:
            displayName: CompanyId
            type: integer
            example: 14146
            description: |
                Identifier for the {{Company}} 
            required: true
        
        VendorIds:
            displayName: VendorIds
            type: string
            example: 1217
            description: |
                List of comma seperated integers representing identifiers for {{Vendors}} 
            required: false
        
        ManufacturerIds:
            displayName: ManufacturerIds
            type: string
            example: 10540
            description: |
                Array of integers representing identifiers for {{Manufacturers}} 
            required: false
        
        IsDropShippable:
            displayName: IsDropshippable
            type: string
            example: true
            description: |
                True to display products available for shipping, false to display products not available for shipping 
            required: false
        
        CategoryOrClassificationId:
            displayName: CategoryOrClassificationId
            type: string
            example: 4
            description: |
                Identifier for the {{Category}} or {{Classification}} 
            required: false
        
        ClassificationTreeId:
            displayName: ClassificationTreeId
            type: string
            example: 1
            description: |
                Identifier for a {{ClassificationTree}} to search within. If CategoryOrClassificationId is provided, this value is ignored 
            required: false
        
        SearchTerms:
            displayName: SearchTerms
            type: string
            example: iPhone
            description: |
                Search terms 
            required: false
        
        OrderBy:
            displayName: OrderBy
            type: string
            example: name
            description: |
                A string value representing which field to order the results by. Acceptable values are name or dateAdded. Defaults to name if not specified 
            required: false
        
        OrderDir:
            displayName: OrderDir
            type: string
            example: asc
            description: |
                A string value representing the sort direction. Acceptable values are asc and desc. Defaults to asc if not specified 
            required: false
        
        PrivateProduct:
            displayName: PrivateProduct
            type: string
            example: false
            description: |
                A flag to indicate if the search should be restricted to Private Products 
            required: false
        
        ColorTagIds:
            displayName: ColorTagIds
            type: string
            example: 1
            description: |
                Array of integers representing identifiers for {{ColorTags}} 
            required: false
        
        Page:
            displayName: Page
            type: string
            example: 1
            description: |
                Page to display, if not specified defaults to 1 
            required: false
        
        PageSize:
            displayName: PageSize
            type: string
            example: 10
            description: |
                Number of results that will be returned, if not specified defaults to 20 
            required: false
          
      
    get:
        displayName: Combining Search Filters
        headers:
            
            Authorization:
                example: Bearer (Access Token)
            
            Accept:
                example: application/json
            
        body:
            
    
