#%RAML 0.8
title: cost-feed
baseUri: https://dropshipdemo.iqmetrix.net/v1

/Suppliers({SupplierId})/Cost:
    uriParameters:
        
        SupplierId:
            displayName: SupplierId
            type: string
            example: 14107
            description: |
                Identifier of the Supplier 
            required: true
          
      
    post:
        displayName: Adding a Product to Cost Feed
        headers:
            
            Authorization:
                example: Bearer (Access Token)
            
            Accept:
                example: application/json
            
            Content-Type:
                example: application/json
            
        body:
            
            application/json:
                
                
                example: |  
                    {"Id":"2e18496c-8f73-4298-8c96-a07816926734","Products":[{"Sku":"1115884","Cost":12.99,"CompanyIds":[14146]}]}
                
            
    
