#%RAML 0.8
title: reference
baseUri: https://referencedemo.iqmetrix.net/v1

/Countries:
    uriParameters:
          
      
    get:
        displayName: Getting All Countries
        headers:
            
            Accept:
                example: application/json
            
        body:
            
    

/TimeZones:
    uriParameters:
          
      
    get:
        displayName: Getting All Time Zones
        headers:
            
            Accept:
                example: application/json
            
        body:
            
    

/Currencies:
    uriParameters:
          
      
    get:
        displayName: Getting All Currencies
        headers:
            
            Accept:
                example: application/json
            
        body:
            
    
