#%RAML 0.8
title: saccs
baseUri: https://shippingaggregatordemo.iqmetrix.net/

/Companies({CompanyId})/ShippingInformation:
    uriParameters:
        
        CompanyId:
            displayName: CompanyId
            type: integer
            example: 14146
            description: |
                Identifier of the Company 
            required: true
          
      
    post:
        displayName: Retrieving Shipping Options
        headers:
            
            Authorization:
                example: Bearer (Access Token)
            
            Accept:
                example: application/json
            
            Content-Type:
                example: application/json
            
        body:
            
            application/json:
                
                
                example: |  
                    {"LocationEntityId":"14202","PostalCode":"P9H 9I4","Items":[{"CatalogId":"18e039de-f950-4d8e-a48a-d06e4db55a07","Quantity":1,"Cost":9.99}]}
                
            
    
