#%RAML 0.8
title: supplier availability
baseUri: https://dropshipdemo.iqmetrix.net/v1

/Suppliers({SupplierId})/Availability:
    uriParameters:
        
        SupplierId:
            displayName: SupplierId
            type: integer
            example: 14107
            description: |
                Identifier for the {{Supplier}} 
            required: true
          
      
    post:
        displayName: Configuring Product Availability
        headers:
            
            Authorization:
                example: Bearer (Access Token)
            
            Accept:
                example: application/json
            
            Content-Type:
                example: application/json
            
        body:
            
            application/json:
                
                
                example: |  
                    {"Id":"c2a97823-196b-4b3e-891a-ba01665797e4","Products":[{"IsAvailable":true,"Sku":"9101AGAP6","Quantity":10}]}
                
            
    
