#%RAML 0.8
title: Trade-In Reporting Service
baseUri: https://tradeinreportingdemo.iqmetrix.net/v1

/providers({ProviderId})/tradeData:
    uriParameters:
        
        ProviderId:
            displayName: ProviderId
            type: integer
            example: 10
            description: |
                The provider identifier given by iQmetrix 
            required: true
          
      
    post:
        displayName: Create or Update a Trade
        headers:
            
            Authorization:
                example: Bearer (Access Token)
            
        body:
            
            application/json:
                
                
                example: |  
                    [{"inspectedDate":"2016-03-16T12:00:00.000Z","originalCustomerInspectionValue ":310.5,"originalCustomerTradeInValue":310.5,"paymentDate":"2016-03-16T12:00:00.000Z","postInspectionValue":310.5,"processedDate":"2016-03-17T12:00:00.000Z","receivedDate":"2016-03-16T12:00:00.000Z","receivedImei":"351756051523999","receivedProductDisplayName":"Galaxy S6 edge+ 32GB - Black Sapphire","referenceNumber":"123","serialNumber":"B7FQ-RANC","shippedDate":"2016-03-13T12:00:00.000Z","shipmentId":"123","tradeInStatus":"Quoted"}]
                
            
    

/providers({ProviderId})/tradeData({TradeDataId}):
    uriParameters:
        
        ProviderId:
            displayName: ProviderId
            type: integer
            example: 10
            description: |
                The provider identifier given by iQmetrix 
            required: true
        
        TradeDataId:
            displayName: TradeDataId
            type: integer
            example: 357
            description: |
                The identifier for the Provider trade-In data 
            required: true
          
      
    get:
        displayName: Get Provider Data for a Trade
        headers:
            
            Authorization:
                example: Bearer (Access Token)
            
        body:
            
    
