#%RAML 0.8
title: vmi
baseUri: https://vmidemo.iqmetrix.net/VMIService.asmx

/?op=GetPendingCompanies:
    uriParameters:
          
      
    post:
        displayName: Getting Pending Companies
        headers:
            
        body:
            
            application/xml:
                
                
                example: |
                    <?xml version="1.0" encoding="utf-8"?>
<soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
  <soap:Body>
    <GetPendingCompanies xmlns="http://www.iqmetrix.com">
      <vendor>
        <VendorID>009E800D-10ED-4F4A-B86F-DFB3C2A18C09</VendorID>
        <Username>danssupplies</Username>
        <Password>samplepassword</Password>
        <Client>
          <ClientID>c46ccb4d-2d44-4289-950a-b9cb51d58ac4</ClientID>
          <Name>DropshipTestDemo</Name>
          <StoreID>4</StoreID>
        </Client>
      </vendor>
    </GetPendingCompanies>
  </soap:Body>
</soap:Envelope>          

                
            
    

/?op=GetCompanyList:
    uriParameters:
          
      
    post:
        displayName: Getting Enabled Companies
        headers:
            
        body:
            
            application/xml:
                
                
                example: |
                    <?xml version="1.0" encoding="utf-8"?>
<soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
  <soap:Body>
    <GetCompanyList xmlns="http://www.iqmetrix.com">
      <Vendor>
        <VendorID>009E800D-10ED-4F4A-B86F-DFB3C2A18C09</VendorID>
        <Username>danssupplies</Username>
        <Password>samplepassword</Password>
        <Client>
          <ClientID>c46ccb4d-2d44-4289-950a-b9cb51d58ac4</ClientID>
          <Name>DropshipTestDemo</Name>
          <StoreID>4</StoreID>
        </Client>
      </Vendor>
    </GetCompanyList>
  </soap:Body>
</soap:Envelope>          

                
            
    

/?op=GetStoreList:
    uriParameters:
          
      
    post:
        displayName: Getting Enabled Stores
        headers:
            
        body:
            
            application/xml:
                
                
                example: |
                    <?xml version="1.0" encoding="utf-8"?>
<soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
  <soap:Body>
    <GetStoreList xmlns="http://www.iqmetrix.com">
      <Vendor>
        <VendorID>009E800D-10ED-4F4A-B86F-DFB3C2A18C09</VendorID>
        <Username>danssupplies</Username>
        <Password>samplepassword</Password>
        <Client>
          <ClientID>c46ccb4d-2d44-4289-950a-b9cb51d58ac4</ClientID>
          <Name>DropshipTestDemo</Name>
          <StoreID>4</StoreID>
        </Client>
      </Vendor>
    </GetStoreList>
  </soap:Body>
</soap:Envelope>          

                
            
    

/?op=GetInventoryReport:
    uriParameters:
          
      
    post:
        displayName: Getting an Inventory Report
        headers:
            
        body:
            
            application/xml:
                
                
                example: |
                    <?xml version="1.0" encoding="utf-8"?>
<soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
  <soap:Body>
    <GetInventoryList xmlns="http://www.iqmetrix.com">
      <Vendor>
        <VendorID>009E800D-10ED-4F4A-B86F-DFB3C2A18C09</VendorID>
        <Username>danssupplies</Username>
        <Password>samplepassword</Password>
        <Client>
          <ClientID>c46ccb4d-2d44-4289-950a-b9cb51d58ac4</ClientID>
          <Name>DropshipTestDemo</Name>
          <StoreID>4</StoreID>
        </Client>
      </Vendor>
      <StartDate>01/01/2016</StartDate>
      <EndDate>10/31/2016</EndDate>
    </GetInventoryList>
  </soap:Body>
</soap:Envelope>          

                
            
    

/?op=CreatePurchaseOrder:
    uriParameters:
          
      
    post:
        displayName: Creating a Purchase Order
        headers:
            
        body:
            
            application/xml:
                
                
                example: |
                    <?xml version="1.0" encoding="utf-8"?>
<soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
  <soap:Body>
    <CreatePurchaseOrder xmlns="http://www.iqmetrix.com">
      <vendor>
        <VendorID>009E800D-10ED-4F4A-B86F-DFB3C2A18C09</VendorID>
        <Username>danssupplies</Username>
        <Password>samplepassword</Password>
        <Client>
          <ClientID>c46ccb4d-2d44-4289-950a-b9cb51d58ac4</ClientID>
          <Name>DropshipTestDemo</Name>
          <StoreID>14070</StoreID>
        </Client>
      </vendor>
      <PurchaseOrder>
        <PurchaseOrderID>4aca5c49-7efd-4ff3-8bbc-70e2fb5e1cf6</PurchaseOrderID>
        <PurchaseOrderData>
          <PurchaseOrderID>4aca5c49-7efd-4ff3-8bbc-70e2fb5e1cf6</PurchaseOrderID>
          <RetailiQPurchaseOrderID>5</RetailiQPurchaseOrderID>
          <RetailiQPurchaseOrderNumber>TT101PO4</RetailiQPurchaseOrderNumber>
          <ShipToStoreID>4</ShipToStoreID>
          <ShipToVendorAccountNumber />
          <BillToStoreID>4</BillToStoreID>
          <BillToVendorAccountNumber>BTTTL101</BillToVendorAccountNumber>
          <OrderTotal>110.90</OrderTotal>
          <ShippingTotal>100.60</ShippingTotal>
          <VendorInvoiceNumber>BDP123</VendorInvoiceNumber>
          <EstimatedArrivalDate>05/10/2016</EstimatedArrivalDate>
          <Comments>Vendor Invoice Number #: BDP123</Comments>
          <ShipToStoreName>Tasha's Test Location</ShipToStoreName>
          <BillToStoreName>Tasha's Test Location</BillToStoreName>
          <VendorName>Dan's Supplies</VendorName>
          <CreatedByVMI>true</CreatedByVMI>
          <CreatedDate>2016-04-07T00:00:00</CreatedDate>
          <IsDeleted>false</IsDeleted>
        </PurchaseOrderData>
        <ProductsOrdered>
          <ProductInformation>
            <ProductID>00000000-0000-0000-0000-000000000000</ProductID>
            <ProductSKU>SSSATM000002</ProductSKU>
            <VendorSKU>SSGS5CB</VendorSKU>
            <ProductItemID>28</ProductItemID>
            <ProductName>Samsung Galaxy S5 - Charcoal Black</ProductName>
            <MaximumLevel>100</MaximumLevel>
            <MinimumLevel>10</MinimumLevel>
            <ProductCost>130.00</ProductCost>
            <QuantityInStock>1</QuantityInStock>
            <QuantityOnOrder>2</QuantityOnOrder>
            <QuantityOnUncommittedOrder>2</QuantityOnUncommittedOrder>
            <QuantityOnBackOrder>0</QuantityOnBackOrder>
            <QuantityInTransfer>1</QuantityInTransfer>
            <QuantityOnRMA>1</QuantityOnRMA>
            <QuantityOnLoan>0</QuantityOnLoan>
            <QuantityCommittedOnOrderEntry>0</QuantityCommittedOnOrderEntry>
            <QuantitySuggestedByVendor>10</QuantitySuggestedByVendor>
            <QuantitySold>20</QuantitySold>
            <GrossQuantitySold>50</GrossQuantitySold>
            <GrossQuantityReturned>2</GrossQuantityReturned>
            <QuantityOrdered>11</QuantityOrdered>
            <QuantityReceived>12</QuantityReceived>
            <DateReceived>2016-04-07T00:00:00</DateReceived>
            <ProductReceived>false</ProductReceived>
            <Enabled>true</Enabled>
            <MinMaxLocked>true</MinMaxLocked>
            <DoNotOrder>false</DoNotOrder>
            <DateEOL>2016-06-01T00:00:00</DateEOL>
            <RetailPrice>685</RetailPrice>
            <SalePrice>550</SalePrice>
            <SaleBegin>2016-05-11T00:00:00</SaleBegin>
            <SaleEnd>2016-05-15T00:00:00</SaleEnd>
          </ProductInformation>
          ...
        </ProductsOrdered>
      </PurchaseOrder>
    </CreatePurchaseOrder>
  </soap:Body>
</soap:Envelope>

                
            
    

/?op=CreatePurchaseOrderShipmentNotice:
    uriParameters:
          
      
    post:
        displayName: Creating a Purchase Order Shipment Notice
        headers:
            
        body:
            
            application/xml:
                
                
                example: |
                    <?xml version="1.0" encoding="utf-8"?>
<soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
  <soap:Body>
    <CreatePurchaseOrderShipmentNotice xmlns="http://www.iqmetrix.com">
      <vendor>
        <VendorID>009E800D-10ED-4F4A-B86F-DFB3C2A18C09</VendorID>
        <Username>danssupplies</Username>
        <Password>samplepassword</Password>
        <Client>
          <ClientID>c46ccb4d-2d44-4289-950a-b9cb51d58ac4</ClientID>
          <Name>DropshipTestDemo</Name>
          <StoreID>14070</StoreID>
        </Client>
      </vendor>
      <notice>
        <PurchaseOrderShipmentNotice>
          <PurchaseOrderID>bcaeea15-5a6d-4515-ba0c-70032da67e8d</PurchaseOrderID>
          <ProductItemID>28</ProductItemID>
          <Quantity>1</Quantity>
          <RQPurchaseOrderID>22073</RQPurchaseOrderID>
          <SerialNumbers>
            <string>490154203237518</string>
            ...
          </SerialNumbers>
          <ShipmentNumber>DSSPOSN1234</ShipmentNumber>
          <VendorInvoiceNumber>POSN1234</VendorInvoiceNumber>
          <VendorSKU>SSGS5CB</VendorSKU>
        </PurchaseOrderShipmentNotice>
        ...
      </notice>
    </CreatePurchaseOrderShipmentNotice>
  </soap:Body>
</soap:Envelope>

                
            
    

/?op=EnableCompany:
    uriParameters:
          
      
    post:
        displayName: Enabling or Disabling a Company
        headers:
            
        body:
            
            application/xml:
                
                
                example: |
                    <?xml version="1.0" encoding="utf-8"?>
<soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
  <soap:Body>
    <EnableCompany xmlns="http://www.iqmetrix.com">
      <vendor>
        <VendorID>009E800D-10ED-4F4A-B86F-DFB3C2A18C09</VendorID>
        <Username>danssupplies</Username>
        <Password>samplepassword</Password>
        <Client>
          <ClientID>c46ccb4d-2d44-4289-950a-b9cb51d58ac4</ClientID>
          <Name>DropshipTestDemo</Name>
          <StoreID>14070</StoreID>
        </Client>
      </vendor>
      <isEnabled>true</isEnabled>
    </EnableCompany>
  </soap:Body>
</soap:Envelope>          

                
            
    
