#%RAML 0.8
title: Authentication
version: v1
baseUri: https://accounts{UrlSuffix}.iqmetrix.net/{version} 
baseUriParameters:
  UrlSuffix:
    description: Suffix that defines the environment
    example: int
    type: string
documentation:
  - title: overview
    content: |
        iQmetrix APIs are protected by [OAuth2](/api/glossary/#oauth).

        In order to make authorized requests to iQmetrix APIs, your application must first obtain an [Access Token](/api/glossary/#access-token).

        ### Postman

        iQmetrix uses <a href="http://www.getpostman.com">Postman</a> when <a href="/api/#testing-and-debugging">testing and debugging</a> our APIs.

        For Chrome or Mac users, click the button below to import the collection directly into Postman.

        <div class="postman-run-button"
        data-postman-action="collection/import"
        data-postman-var-1="e9ae2435064b12fd1b1d"></div>
        <script type="text/javascript">
          (function (p,o,s,t,m,a,n) {
            !p[s] && (p[s] = function () { (p[t] || (p[t] = [])).push(arguments); });
            !o.getElementById(s+t) && o.getElementsByTagName("head")[0].appendChild((
              (n = o.createElement("script")),
              (n.id = s+t), (n.async = 1), (n.src = m), n
            ));
          }(window, document, "_pm", "PostmanRunObject", "https://run.pstmn.io/button.js"));
        </script>

        Alternatively, you can download the collection by clicking <a href="https://www.getpostman.com/collections/e9ae2435064b12fd1b1d">here</a>.

  - title: errors
    content: |
        For troubleshooting, see [Authentication FAQ](/faq/auth-faq).

        | HTTP Status Code | Description | How to Resolve |
        |:-----------------|:------------|:---------------|
        | `HTTP 400` | `unsupported_grant_type` | Ensure grant_type is set appropriately |
        | `HTTP 400` | `invalid_client` | Ensure client_id and client_secret are correct |
        | `HTTP 400` | `invalid_grant` | Ensure client credentials are correct. For a refresh token, ensure credentials are the same as those used to acquire the original access token  |
schemas: 
  - AuthInfo: |
      {
        "name": "AuthInfo",
        "exclude": "true",
        "type": "object",
        "$schema": "http://json-schema.org/draft-03/schema",
        "properties": {
          "access_token": { "type": "string", "putDescription": "The access token issued by the authorization server", "example": "3dae10c05e894011b5b3ae15972ffbf4" },
          "expires_in": { "type": "integer", "putDescription": "Seconds remaining until the access token expires, **12 hours** or less if revoked", "example": "43199" },
          "refresh_token": { "type": "string", "putDescription": "The refresh token generated by the authorization server, expires after **7 days**", "example": "f8bk56n40f7gi34j49g7bh4n430gf874h" }
        }
      }
/oauth2/token:
  post:
    displayName: Obtaining an Access Token
    description: |
      This request will allow you to use the access credentials you received in your onboarding package to get an Access Token.

      #### Notes

      * Each time this request is made, a **new** access token is created and returned
      * As long as an access token is not expired, it can be used to authorize requests to **ANY** iQmetrix API
      * When obtaining or refreshing an access token, ensure the request parameters (e.g. grant_type) are set in the **body** of the request        
    body:
      application/x-www-form-urlencoded:
        formParameters:
          grant_type: 
            type: string
            description: The value must be password
            example: password
            required: true
          username:
            type: string
            description: The username provided to iQmetrix, usually an email address
            example: email@example.com
            required: true
          password:
            type: string
            description: The password, provided when an account is created
            example: examplepassword
            required: true
          client_id:
            type: string
            description: The client ID, provided by iQmetrix
            example: exampleclient
            required: true
          client_secret:
            type: string
            description: The client secret
            example: examplesecret
            required: true
    responses:
      200:
        body:
          application/json:
            schema: AuthInfo
/oauth2/Token:
  post:
    displayName: Refreshing an Access Token
    description: |
      Instead of always using credentials, a client application may use the refresh token to obtain a new access token.

      #### Notes

      * Once a refresh token has been exchanged, the access token it was provided with is revoked
      * The client credentials must be the same as those used in the request to acquire the provided refresh token
      * When obtaining or refreshing an access token, ensure the request parameters (e.g. grant_type) are set in the **body** of the request.
    body:
      application/x-www-form-urlencoded:
        formParameters:
          grant_type: 
            type: string
            description: The value must be refresh_token
            example: refresh_token
            required: true
          client_id:
            type: string
            description: The client ID, provided by iQmetrix
            example: exampleclient
            required: true
          client_secret:
            type: string
            description: The client secret
            example: examplesecret
            required: true
          refresh_token:
            type: string
            description: The refresh token we are exchanging
            example: f8bk56n40f7gi34j49g7bh4n430gf874h
            required: true
    responses:
      200:
        body:
          application/json:
            schema: AuthInfo